
import { ShieldCheck, Cpu, Database, Eye, Lock, AlertTriangle, ArrowLeft } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';

const SECTIONS = [
  {
    icon: AlertTriangle,
    title: 'Data is simulated',
    body: 'All sensor readings, occupancy counts, bin levels, traffic and reports in this demo are generated by a client-side simulator. They are NOT real measurements from any real facility — the Greenfield Institute of Technology campus is fictional. Building footprints are illustrative rectangles drawn from scratch, not surveyed polygons, and the map is fully self-contained with no external tile or font requests.',
  },
  {
    icon: Database,
    title: 'How the simulator works',
    body: 'A seeded PRNG (mulberry32) drives deterministic, reproducible signal generators per sensor kind: PM2.5 with diurnal peaks and spike events, timetable-driven occupancy, meal-time bin fill rates, occupancy/temperature-driven energy and water, and class-change traffic surges. Seven days of 15-minute history are pre-generated on load, then the simulation ticks forward live (1 tick = 15 simulated minutes at 1×). Scheduled anomaly injections guarantee a demo story: a hostel bin overflow forecast, a canteen PM2.5 spike at lunch, a night water-leak signature, an after-hours energy anomaly and a pre-event parking surge.',
  },
  {
    icon: Cpu,
    title: 'Models used',
    body: 'Anomaly detection: rolling z-score (32-point window ≈ 8h) with EWMA-smoothed baseline, threshold z=3, plus a simplified isolation-forest-style multivariate score for ranking. Forecasting: Holt-Winters additive exponential smoothing with a 24h seasonal cycle and a 1.28σ residual prediction interval (seasonal-naive fallback for short series). Bin overflow ETA: linear fill-rate extrapolation with a time-of-day multiplier. All models run in the browser in TypeScript.',
  },
  {
    icon: Eye,
    title: 'Explainability',
    body: 'Every alert carries a "Why this fired" panel: the rule or model, observed vs expected values, threshold, time window, confidence and assumptions. Every recommendation shows its rationale, expected impact, owner role and assumptions. The recommendation engine is rules + forecasts + plain-language templates — it is NOT an LLM. An LLMProvider interface with a stub is provided so a real GenAI call could be plugged in later.',
  },
  {
    icon: Lock,
    title: 'Privacy stance',
    body: 'Occupancy is aggregate-only — the system never tracks individuals. Citizen reports are anonymous by default and stored only in the browser (localStorage via Zustand persist). No data leaves the device; there is no backend, analytics or third-party call. The design follows DPDP Act 2023 and GDPR-aware principles: data minimisation, purpose limitation, local-first storage.',
  },
  {
    icon: ShieldCheck,
    title: 'Limitations',
    body: 'Forecasts are short-horizon (1–6h) and assume recent patterns persist. The isolation-forest-style score is a simplified ranking heuristic, not a production model. Scenario projections are first-order multipliers, not physics-based. The sustainability scorecard is a heuristic composite with editable weights, not a certified audit. CO2e uses a configurable grid emission factor (default 0.72 kg/kWh, India grid average per CEA). Map tiles require network access; the app degrades gracefully to an offline basemap when tiles fail.',
  },
];

export default function AboutPage() {
  return (
    <div className="h-full overflow-y-auto bg-[#000000] p-4 md:p-6">
      <div className="mx-auto max-w-3xl">
        <div className="mb-4 flex items-center gap-3">
          <Button variant="ghost" size="sm" className="gap-1" asChild>
            <Link to="/">
              <ArrowLeft size={12} />
              Back
            </Link>
          </Button>
          <div>
            <h1 className="font-display text-xl font-bold tracking-wider text-[#fafafa]">
              Assumptions & Method
            </h1>
            <p className="text-xs text-muted-foreground">
              Everything you need to know about what this demo is — and is not.
            </p>
          </div>
          <Badge variant="warning" className="ml-auto">
            Simulated data
          </Badge>
        </div>

        <div className="space-y-3">
          {SECTIONS.map(({ icon: Icon, title, body }) => (
            <Card key={title} className="hud-corner">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Icon size={14} className="text-data" />
                  {title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs leading-relaxed text-muted-foreground">{body}</p>
              </CardContent>
            </Card>
          ))}
        </div>

        <Card className="mt-4 border-warn/30">
          <CardContent className="pt-4 text-center">
            <p className="font-hud text-sm font-bold uppercase tracking-wider text-warn">
              Decision-support insights, not official measurements.
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Terrascope demo · Cognizant hackathon · Team Vintage · BH26PS04T004
            </p>
          </CardContent>
        </Card>

      </div>
    </div>
  );
}
